# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(829, 628)

        self.current_braille = ""
        self.braille_dict = {
            ' ': ' ',
            'a': '⠁',
            'b': '⠃',
            'c': '⠉',
            'd': '⠙',
            'e': '⠑',
            'f': '⠋',
            'g': '⠛',
            'h': '⠓',
            'i': '⠊',
            'j': '⠚',
            'k': '⠅',
            'l': '⠇',
            'm': '⠍',
            'n': '⠝',
            'o': '⠕',
            'p': '⠏',
            'q': '⠟',
            'r': '⠗',
            's': '⠎',
            't': '⠞',
            'u': '⠥',
            'v': '⠧',
            'w': '⠺',
            'x': '⠭',
            'y': '⠽',
            'z': '⠵',
            '\n': '\n'
        }


        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(120, 100, 571, 201))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(370, 370, 47, 16))
        self.label.setObjectName("label")
        self.printbutton = QtWidgets.QPushButton(Dialog)
        self.printbutton.setGeometry(QtCore.QRect(230, 470, 151, 41))
        self.printbutton.setObjectName("printbutton")
        self.cancelbutton = QtWidgets.QPushButton(Dialog)
        self.cancelbutton.setGeometry(QtCore.QRect(400, 470, 151, 41))
        self.cancelbutton.setObjectName("cancelbutton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 70, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.printbutton.clicked.connect(lambda: self.printbutton_clicked("Printed clicked"))
        self.textEdit.textChanged.connect(self.update_braille)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Braille-iant", "Braille-iant"))
        self.label.setText(_translate("Dialog", "Braille"))
        self.printbutton.setText(_translate("Dialog", "PRINT"))
        self.cancelbutton.setText(_translate("Dialog", "CANCEL"))
        self.label_2.setText(_translate("Dialog", "Enter Text:"))

    def printbutton_clicked(self, text):
        self.label.setText(text)
        self.label.adjustSize()

    def update_braille(self):
        self.current_braille = " "
        print(str(self.textEdit.toPlainText()))
        for char in str(self.textEdit.toPlainText()):
            self.current_braille = self.current_braille + self.braille_dict[char]
        self.label.setText(self.current_braille)
        self.label.adjustSize()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
